lang: en
locale: en-US
headerSeparator: "|"
author: Brandtley McMinn
description: Professional site of Brandtley McMinn, all around nerd and maker enthusiast from Austin, TX
title: Gbox Studios
backgroundColor: '#fff'
